### PR TITLE
Added in Attack Button which makes Inventory show when its clicked

### LINKED ISSUE #27: Tile Interactions
- [x] Tile Menu: Attacking Tiles button, only shows on enemy tiles during your turn
- [x] Building Menu: Shows on friendly tiles, build( if tile empty), destroy, stop

### PR DESCRIPTION
**Pull request by Snapshot0010**
Added in an attack Button which will show up when the current player clicks on a tile that is not theirs. If the player then clicks on the attack Button, the inventory will show up. If the player wishes to cancel the attack, the can click the escape key which will make the attack button disappear. Also added in a simple getter for tilesOwned. Thought I was gonna need it originally for the button, but realized there was a better way of doing it. However, I decided to keep it in as it could be useful in the future. 

Resolves #27

### CODE REVIEW

**Review by GNAR1ZARD — DISMISSED** [review]
The implementation of the AttackButton functionality seems to be working as intended, nicely toggling the inventory view.

**Review by nathalmg — APPROVED** [review]
The AttackButton Implementation switching to the Inventory for the cards is a nice touch  and will help players that are new to the genre easily adapt to the game.

**Review by Joeyo364 — DISMISSED** [review]
Code is neat and the attack button works as intended. Overall good job with this implementation.

**Review by zmorgancs — APPROVED** [review]
This looks good, the only concern I have is that deactivating an attack uses the escape key, which I was under the assumption would open/close the escape menu alongside the menu button. We will most likely have further discussions about specific keymappings however so I think it's fine how escape is used in this script, Good work.

**Review by zmorgancs — APPROVED** [review]
Submitting re-approval for new changes.

**Review by nathalmg — DISMISSED** [review]
Submitting reapproval.

**Review by nathalmg — APPROVED** [review]
Reapproving again, changes to the meta file should be okay.

**Pull request merged**
