### PR TITLE
Edit tests

### PR DESCRIPTION
**Pull request by Grimmblood**
## Describe your changes
Added a test suite for the Building class, and added an (incomplete) test suite for the Tile class.

## Issue number and link
N/A

## Types of changes
- [ ] Bug fix (fixes a issue)
- [x] New feature (new implemention of a feature)
- [ ] Refactoring (small changes that won't impact very much)
- [ ] Possible broken change (fix or feature that could break functionality)

## Checklist:
- [x] Have added comments and documentation
- [x] I have added tests to cover my changes. 
   Or have added an issue that tests need to be added.

### CODE REVIEW

**Review by GNAR1ZARD — APPROVED** [review]
Adding tests for the Building class and starting the Tile class test suite demonstrates attention to code quality and stability.

**Review by CodingAdam — APPROVED** [review]
Approving but make sure to remove tile tests before merging. However buildings tests look good and I assumed they work.

**Review by GNAR1ZARD — APPROVED** [review]
Good job for the hot patch to fix the issues. Approving

**Review by CodingAdam — APPROVED** [review]
Approving again thanks for changing it.

**Pull request merged**
