### PR TITLE
Fixing Pipeline 

### PR DESCRIPTION
**Pull request by GNAR1ZARD**
Updated any outdated GitHub Actions to their latest supported versions.

### CODE REVIEW

**Comment by GNAR1ZARD** [comment]
Screenshot 2024-03-07 145807

@CodingAdam

**Comment by CodingAdam** [comment]
Looks like the pipeline works now, literally just has some errors regarding scripts that have issues that #36 mentions.

**Comment by GNAR1ZARD** [comment]
I updated the issue with a comment explaining in detail the situation.

**Review by CodingAdam — APPROVED** [review]
Approving, the pipeline itself should be good unless we need another token in the .yml. Unless this should finally work.

**Comment by GNAR1ZARD** [comment]
Ok, added an additional token for scope permissions. Apparently even that didnt do it. Now I have to request permissions to configure a github app with necessary permissions for the repo. 
image

**Comment by GNAR1ZARD** [comment]
The remaining issue(s) seem to be with the project and not the pipeline itself. Merging and closing the PR.

**Review by GNAR1ZARD — COMMENTED** [review]
This PR had two approvals. I didnt realize another two approvals were necessary so I forced the merge considering there were no conflicts to move things along.

**Pull request merged**
