### PR TITLE
Add Abstract CardClass

### PR DESCRIPTION
**Pull request by SibeW**
### Description
In correlation with Issue  #10 
Added an abstract card class for future use. This class contains a struct for storing the stats of the individual card. There are also basic getters/setters for each stat of the card. The class also has a GameObject card, this is for displaying an actual card in Unity. I wrote a method for setting the card's status to active, which activates the object in-game.

### CODE REVIEW

**Comment by CodingAdam** [comment]
Nice got everything I need we'll need starting off with. Interesting use of the struct for the stats of the card, not sure if it's necessary but we'll see, maybe it being a struct will be useful later on. Otherwise I think this will work, I'll keep the reviews open so more people can review and look over it.

**Review by Grimmblood — APPROVED** [review]
Looks good. May need to add a way to hide the card, but that can be easily done later.

**Review by Snapshot0010 — APPROVED** [review]
I don't see any issues with these changes. Also, good note at making sure to preemptively add in limits for the defense and offense stats for cards. While it is likely these will end up being changed later the fact that you added them earlier just means we won't have to do so in the future, so good job. The only thing I'm not sure about is creating a struct. As it is now, I think its somewhat redundant, but not a massive deal. I would say probably keep it for now as it doesn't add too much bulk and could prove to be very helpful going forward.

**Comment by Snapshot0010** [comment]
I am going to close this pull request and the associated issue as it appears that the abstract card class is done.
Closes #10

**Pull request merged**
