### PR TITLE
fixed compilation error in PlayerList

### PR DESCRIPTION
**Pull request by Grimmblood**
## Describe your changes
Added a method in PlayerController to get the current player, and implemented that into the PlayerList class.

## Issue number and link
N/A

## Types of changes
- [x] Bug fix (fixes a issue)
- [ ] New feature (new implemention of a feature)
- [x] Refactoring (small changes that won't impact very much)
- [ ] Possible broken change (fix or feature that could break functionality)

## Checklist:
- [ ] Have added comments and documentation
- [ ] I have added tests to cover my changes. 
   Or have added an issue that tests need to be added.

### CODE REVIEW

**Review by Joeyo364 — DISMISSED** [review]
Approving to fix compilation error on master branch.

**Comment by Grimmblood** [comment]
Temporarily disabled the PlayMode Test for BuildButtonScript following large changes to BuildButtonScript. (in commits accidentally put TileScript)
Changed the visibility of TileScript's MeshRenderer to not break the TileScript Test.

**Review by Joeyo364 — APPROVED** [review]
Submitting reapproval of these changes.

**Comment by Grimmblood** [comment]
Closing because PR #95 addresses the same thing.

**Pull request closed without merging**
