### PR TITLE
Added Phases (Defense, Attack, Build)

### PR DESCRIPTION
**Pull request by GNAR1ZARD**
## Describe your changes
Player Script Changes:

- Added Phase Enum: Defines the stages each player goes through each turn ("Attack", "Defense", "Build").
- Added currentPhase Variable: Tracks the current phase of the player.
- Added NextPhase() Method: Advances the player to the next phase, looping back after the last phase.
- Added ResetPhase() Method: Resets the player's phase to "Attack" at the start of a new turn.
- Added GetCurrentPhase() Method: Returns the current phase of the player for external checks.

TurnMaster Script Changes:

- Added AllPhasesDone(Player[] players) Method: Checks if all players have completed all phases to transition to a new turn.
- Refactored newTurn(Player[] Players) Method: Now also resets each player's phase to the beginning along with marking the start of a new turn.
- Added AdvancePlayerPhase(Player player) Method: Manually advances a player's phase and checks for phase completion to potentially end their turn.

Reasons for Refactoring:

- Update in TurnMaster: Adjusted to incorporate phase checks, ensuring turn progression only after all phases are completed, to align with the new phased turn system logic.
- newTurn Refactoring: Enhanced to reset phases for each player at the start of a new turn, ensuring a clean slate for the turn and phase progression.

## Issue number and link
Issue https://github.com/UNLV-CS472-672/2024-S-GROUP8-CW/issues/74

## Types of changes
[] Bug fix (fixes a issue)
[x] New feature (new implemention of a feature)
[] Refactoring (small changes that won't impact very much)
[] Possible broken change (fix or feature that could break functionality)

## Checklist:
[x] Have added comments and documentation
[] I have added tests to cover my changes. 
   Or have added an issue that tests need to be added.

### CODE REVIEW

**Comment by CodingAdam** [comment]
Small thing defense phase should come first.

**Comment by GNAR1ZARD** [comment]
Will fix.

**Comment by GNAR1ZARD** [comment]
@CodingAdam Done

**Review by CodingAdam — APPROVED** [review]
Looks good, next step we just need to mount it mechanically into the game. Approving.

**Comment by GNAR1ZARD** [comment]
Will add testing in a subsequent PR

**Pull request merged**
