### PR TITLE
Unit Tests

### PR DESCRIPTION
**Pull request by Grimmblood**
## Describe your changes
Moved and Refactored Unit Tests for: TileScript
Added Unit Tests for the following: AttackButtonScript, BuildButtonScript, CameraScript
Attempted Unit Tests for: EndTurn, EscapeMenu, PlayerController
     for various technical reasons I was unable to progress on Attempted Tests
Results In: ~33% Line Coverage, ~46% Method Coverage

## Issue number and link
Partially Addresses, but does not complete: #76 and #83 

## Screenshots (if appropriate):
image_2024-04-03_210322565

## Types of changes
- [ ] Bug fix (fixes a issue)
- [ ] New feature (new implementation of a feature)
- [x] Refactoring (small changes that won't impact very much)
- [ ] Possible broken change (fix or feature that could break functionality)

## Checklist:
- [x] Have added comments and documentation
- [x] I have added tests to cover my changes. 
   Or have added an issue that tests need to be added.

### CODE REVIEW

**Review by Snapshot0010 — DISMISSED** [review]
Good work on adding Unit Tests for many of the scripts that we already had. These should serve as a good foundation for future testing.

**Comment by Grimmblood** [comment]
I am trying to fix some glaring issues with this, do not merge until I comment that the issues are fixed.

**Comment by Grimmblood** [comment]
Seems like the conflicts are resolved.

**Review by Snapshot0010 — APPROVED** [review]
Changes overall look good, great job on adding more unit tests.

**Pull request merged**
