### PR TITLE
added 3 files (UnitType, buildingScript, cardScript) to address Issue #28

### PR DESCRIPTION
**Pull request by GNAR1ZARD**
#28 This pull request introduces a foundational structure for managing unit production within our game, specifically focusing on the implementation of Card and Building classes, alongside an UnitType enum. The Card class encapsulates the details of individual units, including their type, name, and production cost, while the Building class provides a method to produce these unit cards based on their type, enhancing our game's strategic elements and unit management mechanics. By employing an enum for unit types, we ensure type safety and clarity across the codebase, facilitating easier expansion and maintenance of our unit production system.

### CODE REVIEW

**Comment by CodingAdam** [comment]
This looks great, however I realized some of the abstract classes weren't pushed correctly. As this implementation should've implemented those abstract classes. Not creating their own classes, I.e Heavy Infantry Card extends Card class, or Attacker Card Class extends card class. Something along those lines. That way we could abstract the functionality of the Card class for all possible use cases.

**Review by Snapshot0010 — DISMISSED** [review]
Everything looks fine to me. Don't notice anything that needs to be changed or altered. Good start on implementation for both cards and buildings.

**Comment by CodingAdam** [comment]
> Everything looks fine to me. Don't notice anything that needs to be changed or altered. Good start on implementation for both cards and buildings.



> Everything looks fine to me. Don't notice anything that needs to be changed or altered. Good start on implementation for both cards and buildings.

Ryan needs to refactor this PR so please don’t merge it until then. Btw I mentioned this during the meeting please don’t blindly approve PRs.

**Comment by GNAR1ZARD** [comment]
Broke down the PR in half. Focusing on the cardReg script for now. It creates three unique cards stored in the registry for future reference/actions. The cards are named after programming languages. I left the sprite set to null for now. 

Ill create another PR for the buildingReg.

**Review by CodingAdam — APPROVED** [review]
Good for testing pulling cards from the registry. Subject to change, however good base to add more cards to in future. Approving.

**Review by nathalmg — APPROVED** [review]
Great start to making more cards for our game and providing an easy way to access them by finding the name on the list.

**Pull request merged**
