### PR TITLE
added comprehensive unit testing to increase code coverage - cardRegi…

### PR DESCRIPTION
**Pull request by GNAR1ZARD**
## Describe your changes
Added unit tests for the CardRegistry class to ensure its functionality is correct and consistent.

## Issue number and link
N/A

## Screenshots (if appropriate):
N/A

## Types of changes
- [ ] Bug fix (fixes an issue)
- [ ] New feature (new implementation of a feature)
- [ ] Refactoring (small changes that won't impact very much)
- [ ] Possible broken change (fix or feature that could break functionality)
-[x] Test Coverage

## Checklist:
- [x] Have added comments and documentation
- [x] You have tested all the code thoroughly 
- [x] I have added tests to cover my changes. 
   Or have added an issue that tests need to be added.
- [ ] If scene changes were made were they in a separate scene (Doesn't apply to CodingAdam)

Used ChatGPT to fill in the checklist for the PR and reviewed its contents to verify its accuracy. Here is the link to the conversation: https://chat.openai.com/share/66d1a6ff-afdc-4c51-baab-cc305c59cf51

### CODE REVIEW

**Comment by GNAR1ZARD** [comment]
Encountering significant challenges due to the reliance on Awake() for initializing components in our tests. The method is automatically triggered by Unity's lifecycle when the GameObject becomes active, which complicates controlling test conditions and sequence of operations. -- Might need to scrap unless a workaround solution is known. @CodingAdam

**Comment by CodingAdam** [comment]
> Encountering significant challenges due to the reliance on Awake() for initializing components in our tests. The method is automatically triggered by Unity's lifecycle when the GameObject becomes active, which complicates controlling test conditions and sequence of operations. -- Might need to scrap unless a workaround solution is known. @CodingAdam

I need you to be more specific because awake and start I believe can both be "run through" by grabbing the gameobject the script is stored in. However for this class specifically I was planning on making it a normal class and loading it in GameManager. So I probably will remove the awake situation anyways.

**Comment by GNAR1ZARD** [comment]
Working, comprehensive coverage for CardReg. Awaiting approvals

**Review by CodingAdam — APPROVED** [review]
Simple not much to say, approving. Although thanks for using the new implementation of CardReg.

**Review by Nick8120 — APPROVED** [review]
Good job this test for CardRegistry looks good and will help increase the test coverage for the new implementation. I see a note regarding a way to reset the list which we can look into after finalizing some more thing but approving this PR as is.

**Pull request merged**
