### PR TITLE
pull_request_target is said to use secrets on a fork, so testing

### PR DESCRIPTION
**Pull request by CodingAdam**
Testing testing

### CODE REVIEW

**Comment by CodingAdam** [comment]
I believe this may need to be merge for it to work with anything

**Review by zmorgancs — APPROVED** [review]
Looks good, submitting approval for testing

**Comment by CodingAdam** [comment]
Btw no idea if this actually works because this pr's pipeline no longer functional the way I believe it was supposed to

**Review by Grimmblood — APPROVED** [review]
approving for testing

**Pull request merged**
