### PR TITLE
Added testing cases for Card, CardStack, and TurnMaster

### PR DESCRIPTION
**Pull request by CodingAdam**
## Describe your changes
Added testing cases for Card, CardStack, and TurnMaster. Turnmaster still requires cases for playmode.

## Issue number and link
N/A

## Types of changes
- [ ] Bug fix (fixes a issue)
- [x] New feature (new implementation of a feature)
- [ ] Refactoring (small changes that won't impact very much)
- [ ] Possible broken change (fix or feature that could break functionality)

## Checklist:
- [x] Have added comments and documentation
- [x] I have added tests to cover my changes. 
   Or have added an issue that tests need to be added.

### CODE REVIEW

**Comment by CodingAdam** [comment]
Still need to add comments

**Review by Grimmblood — APPROVED** [review]
Looks good. Lots of files O.o

**Review by GNAR1ZARD — APPROVED** [review]
The addition of test cases for the Card, CardStack, and TurnMaster classes is a significant step towards validating the game logic and ensuring the robustness of the turn mechanics.

**Review by Nick8120 — APPROVED** [review]
The unit tests added in this PR look good. We might need to add more tests for unexpected behaviors in regards to the CardStackTest and CardTest. Since these tests look good overall  I will approve this PR.

**Pull request merged**
