### PR TITLE
Added Initial Implementation for Build Button

### LINKED ISSUE #77: Finish Building System
Finish up the work for the building system, update each turn with the new buildings. Update system for buildings.

### PR DESCRIPTION
**Pull request by Snapshot0010**
## Describe your changes

Added in the Initial Implementation of the Build Button so that when the player clicks on a tile they control,
the build button appears over that tile. I also refactored the Attack Button to work in the same manner. 
Whenever you click the cancel button which appears with them they will disappear. However,
clicking on the associated build and attack button results in the inventory appearing.

## Issue number and link

Partially Resolves #77 and #89 (Only added in test cases for cancel button as I see that another PR adds in test cases for attack)

## Types of changes
[] Bug fix (fixes a issue)
[X] New feature (new implemention of a feature)
[X] Refactoring (small changes that won't impact very much)
[] Possible broken change (fix or feature that could break functionality)

## Checklist:
[X] Have added comments and documentation
[X] I have added tests to cover my changes. 
   Or have added an issue that tests need to be added.

### CODE REVIEW

**Review by GNAR1ZARD — DISMISSED** [review]
Restoring the attack button and adding a cancel button improves user control during gameplay. Changing the cancel action to a button click, instead of the escape key, aligns with user interface consistency.

**Review by Grimmblood — DISMISSED** [review]
Approving so that work using the secondary canvas can begin.

**Review by Joeyo364 — APPROVED** [review]
These changes will certainly improve the gameplay by giving the user a way to build things in the game. Approving so work may continue.

**Review by CodingAdam — APPROVED** [review]
Approving lots good, I'll need to make it more dynamic but should be a easy task.

**Comment by Grimmblood** [comment]
Approving so we can use this for the current tasks.

**Review by Grimmblood — APPROVED** [review]
Approving so we can use this for the current tasks.

**Pull request merged**
