### PR TITLE
GUI system

### PR DESCRIPTION
**Pull request by CodingAdam**
## Describe your changes
CardRegistry and BuildRegistry are no longer monobehaviors
- #113 should be fine now @GNAR1ZARD 

Cancel button and Turn Button look nicer
Several Classes have received Serialized Fields (easier to change and access while being private)
Defendable icons are now removed 
- On creating a battle
- Ending the phase

Turn button properly ends turns and phases, displaying text based on whether it will end the turn or phase
Tiles now only can be attacked if they are near the player's owned tiles (in a 3 by 3 grid around the selected tile the player wishes to attack)
Fixed a bunch of random issues
- Hand didn't actually transfer cards 
- Removed temp values that were breaking intended functionality
- Etc (Some were very small and hard to remember)

## Issue number and link
Implements  #116,  #117, #118

## Screenshots (if appropriate):
image
- The new look for cancel and new turn/phase

Screenshot 2024-04-21 020208
- Stash icon

## Types of changes
- [X] Bug fix (fixes a issue)
- [X] New feature (new implementation of a feature)
- [X] Refactoring (small changes that won't impact very much)
- [X] Possible broken change (fix or feature that could break functionality)

## Checklist:
- [X] Have added comments and documentation
- [X] You have tested all the code thoroughly 
- [X] I have added tests to cover my changes. 
   Or have added an issue that tests need to be added.
- [X] If scene changes were made were they in a separate scene (Doesn't apply to CodingAdam)

### CODE REVIEW

**Comment by GNAR1ZARD** [comment]
Hey Adam, can you revert the changes made to building registry please? They will definitely cause a conflict and my test script works fine for that class. Thank you buddy

**Comment by CodingAdam** [comment]
> Hey Adam, can you revert the changes made to building registry please? They will definitely cause a conflict and my test script works fine for that class. Thank you buddy

Didn't you just talk about how it was a pain to get the awake function to work? And I responded that I was going remove it, so no I will not revert it. You're just going to have to edit your testing file (for god sake you can basically copy the card one and change a few things). Why did you even make it draft in the first place?

**Comment by GNAR1ZARD** [comment]
@

> Didn't you just talk about how it was a pain to get the awake function to work?

I did but awake only is in cardRegistry. And you did respond stating that you would remove it (which is fine) but you never mentioned anything whatsoever about refactoring buildingRegistry --Especially while I have a working PR waiting on approvals (if you wouldnt mind when you get a chance).

I converted the cardRegistry to draft awaiting your removal of Awake().

Now I kindly ask again for you to revert your changes to building registry atleast until my PR is through and then you can pull it down and make whatever changes you would like. 

Thank you @CodingAdam

**Comment by CodingAdam** [comment]
> @
> 
> > Didn't you just talk about how it was a pain to get the awake function to work?
> 
> I did but awake only is in cardRegistry. And you did respond stating that you would remove it (which is fine) but you never mentioned anything whatsoever about refactoring buildingRegistry --Especially while I have a working PR waiting on approvals (if you wouldnt mind when you get a chance).
> 
> I converted the cardRegistry to draft awaiting your removal of Awake().
> 
> Now I kindly ask again for you to revert your changes to building registry atleast until my PR is through and then you can pull it down and make whatever changes you would like.
> 
> Thank you @CodingAdam

I did though I removed it from both, I won't just remove it from one registry if the issue persists in both. Are you unable to access you pr for changes?

**Comment by CodingAdam** [comment]
I mean if you really cannot do the changes, I'll just approve your prs and then refactor them myself it that is how you want to do it.

**Comment by GNAR1ZARD** [comment]
I'm just awaiting approvals. Its just working test coverage for the buildingReg but I only mentioned it because its going to cause a merge conflict for one of us. My PR was in first so I just assumed simple FIFO.

**Comment by CodingAdam** [comment]
> Dont worry about it. Just put yours through and Ill take care of mine after. Its just test coverage. @CodingAdam

Alright that's fine, I'll wait for two approvals then push this. I got to make changes anyways based on the BuildingButton stuff.

**Review by GNAR1ZARD — APPROVED** [review]
Great work on the updates! Overall, these changes should positively impact the user experience and gameplay mechanics. Approving.

**Review by zmorgancs — APPROVED** [review]
Great work on the visual improvements, and the assorted fixes + addition of serialized fields will make working on this project easier, approving.

**Pull request merged**
