### PR TITLE
Player inventory and scene fix

### LINKED ISSUE #37: Card Stack card object Parameter not used
Just a note when looking at the CardStack class implementation for the functions AddCardToStack(Card card) and RemoveCardFromStack(Card card) the card object in the parameters of the function is never used. Check is needed for if a card matches.

### PR DESCRIPTION
**Pull request by CodingAdam**
Added more inventory stuff for the inventory GUI #26
- Namely combined the player inventory and inventory controller so now they interact
- Added another method for placing cards into the inventory controller based on no index 
- Player now has a inventory object
- Still work in process so this doesn't finish off #26 task 1

Mainly this pr fixes a scene issue hopefully allowing our pr to build 
- Refers to #45 

Edit:
Updated the inventory GUI
- Now shows amount of cards in a stack and the name of the card better
- Fixed removable of cards not working
Also fixes  #37

### CODE REVIEW

**Review by Snapshot0010 — APPROVED** [review]
Overall, changes look good. Good additions to the functionality of the inventory management and associated GUI elements.

**Review by GNAR1ZARD — APPROVED** [review]
It's good to see the inventory system taking shape with the integration of the player inventory and inventory GUI elements. The addition of the method for placing cards without an index and the update to the inventory GUI for displaying card stacks and names are solid improvements.

**Comment by GNAR1ZARD** [comment]
@CodingAdam Issue with conflicts. Try pulling master remote into your local branch and then repushing.

**Review by Joeyo364 — DISMISSED** [review]
Good job adding checks to the inventory system, this will help in the case that a bug arises from the inventory system later in development.

**Review by Snapshot0010 — APPROVED** [review]
Great progress on the inventory system. The changes make sense and either advance the functionality of the inventory or help its clarity.

**Comment by CodingAdam** [comment]
Ok I have no idea why it still cannot build the scenes

**Review by Snapshot0010 — APPROVED** [review]
Since last approval all changes were made in an attempt to have it build successfully in Github. Even though doesn't appear to have worked yet, will approve this as it does not appear it will break anything and the other changes are important to incorporate.

**Review by Joeyo364 — APPROVED** [review]
The scene should hopefully build successfully with these changes.

**Review by Nick8120 — APPROVED** [review]
Overall the changes made in your most recent PR look good. The additions of adding input to the GUI from the update function look correct. SetText() was also a solid addition to easily alter the text. It looks like removing within this implementation might not function properly. This is something that we can change within future refactoring and testing but as of now solid implementation.

**Review by Nick8120 — APPROVED** [review]
The changes you made look good. My previous review of the code still stands and I am approving this PR.

**Review by Joeyo364 — DISMISSED** [review]
Resubmitting approval.

**Review by Joeyo364 — APPROVED** [review]
Resubmitting approval.

**Review by Nick8120 — APPROVED** [review]
Resubmitting approval.

**Pull request merged**
