### PR TITLE
fixBuildBttnTest

### PR DESCRIPTION
**Pull request by GNAR1ZARD**
## Describe your changes
Modified the setup method to ensure the buildButton filed != Null

## Issue number and link
NA

## Types of changes
- [x] Bug fix (fixes a issue)
- [ ] New feature (new implemention of a feature)
- [ ] Refactoring (small changes that won't impact very much)
- [ ] Possible broken change (fix or feature that could break functionality)

## Checklist:
- [x] Have added comments and documentation
- [x] You have tested all the code thoroughly 
- [x] I have added tests to cover my changes. 
   Or have added an issue that tests need to be added.
- [ ] If scene changes were made were they in a separate scene (Doesn't apply to CodingAdam)

### CODE REVIEW

**Comment by GNAR1ZARD** [comment]
Also removed these files:
        deleted:    Crypto Wars/Assets/Scripts/GUI/BuildButtonScript.cs
        deleted:    Crypto Wars/Assets/Scripts/GUI/BuildButtonScript.cs.meta
        
Since its an unnecessary/duplicate test file in the wrong dir.

**Comment by CodingAdam** [comment]
Um why don't you just make a getter for that buildMenu field?

**Review by CodingAdam — APPROVED** [review]
Access is a bit inconsistent, but with the time we have and the fact that you stated that this works, Approving.

**Comment by GNAR1ZARD** [comment]
Guys this was a daunting task but finally fixed the broken test coverage for buildButtonScriptTest which resolved 4-5 failing tests (due to the duplicate file in the wrong dir that was removed).

**Comment by GNAR1ZARD** [comment]
> Um why don't you just make a getter for that buildMenu field?

I was about to use properties --I have them commented out-- to make the private members accessible but I just wanted to get some working test coverage.

**Review by Grimmblood — APPROVED** [review]
Approving so we can see our overall coverage

**Pull request merged**
