### PR TITLE
Escape Menu GUI

### PR DESCRIPTION
**Pull request by zmorgancs**
Added EscapeMenu.cs into the GUI folder to implement the escape menu requirements of issue #51  , which has the ability to:

- Toggle an escape menu via pressing the "escape" key or right clicking the "Menu" button in the top left corner of the game view
- Current menu options are to resume a match, exit to main menu (pending its implementation), open settings menu (pending its implementation) and close the game window.

To test the functionality of this script, I attached it to a default UI Canvas in the Unity Hierarchy.

### CODE REVIEW

**Comment by CodingAdam** [comment]
Currently all I see in the pr, it the script in question. Did you work on the gui element for the escape button. Because currently it doesn't seem to be included here.

**Comment by zmorgancs** [comment]
> Currently all I see in the pr, it the script in question. Did you work on the gui element for the escape button. Because currently it doesn't seem to be included here. Or some way to run the script.

Should I make a prefab to attach the gui element to? I wasn't entirely sure how we would be adding these to our game scene so when testing I just added the script to a canvas object and tried to handle as much in the script as I could as opposed to building the panels/buttons via Unity itself, should I redo this so that more is built with the tools in the Unity software or would it be easier to make a prefab object?

**Review by Snapshot0010 — APPROVED** [review]
Good implementation of the escape menu. Very clever way of implementing the toggle simply setting a bool to the opposite of itself. The menu itself looks to be made well and should be clear for the player.

**Review by Grimmblood — APPROVED** [review]
Looks good. I wish I had thought of handling the GUI toggles like that when I was making the building menu.

**Comment by zmorgancs** [comment]
Closes issue #51

**Pull request merged**
