### PR TITLE
GUI main menu

### LINKED ISSUE #46: Main Menu: Settings page, start game, etc

### PR DESCRIPTION
**Pull request by Nick8120**
This is an implementation of GUI for the main menu.  It adds basic functionality for starting a new game, loading a previous game, and exiting the game. Additionally, I added some additional implementation for volume and graphical settings that scenes that will be options under the 'Settings' options in the main menu. This is my first experience with GUI in unity so if there are any suggestions for optimizations or anything I might need to add please let me know. 

Features to consider adding to this script in the future:
- Gameplay Settings
- Controller/Key Board Settings or bindings
- Resolution
- Reset to default settings

Resolves #46

### CODE REVIEW

**Comment by CodingAdam** [comment]
Does this pr actually have a custom scene or unity GUI element to test the functionality of the main menu?

**Review by Joeyo364 — CHANGES_REQUESTED** [review]
Overall looks good, but as Adam mentioned in order for the game to be loaded from the main menu we will need a custom scene to be added to the 'Scenes' directory. Once that is added the main menu should be in proper working order.

**Comment by CodingAdam** [comment]
> Overall looks good, but as Adam mentioned in order for the game to be loaded from the main menu we will need a custom scene to be added to the 'Scenes' directory. Once that is added the main menu should be in proper working order.

Just letting you know that this PR does contain the scene in question.

**Review by Joeyo364 — DISMISSED** [review]
My mistake, the scene is included.

**Review by Joeyo364 — APPROVED** [review]
Resubmitting approval.

**Pull request merged**
