### PR TITLE
Card selection

### PR DESCRIPTION
**Pull request by CodingAdam**
## Describe your changes
I've added two new classes and a GUI element to be used generically for creating attacks, defenses, and buildings. It serves as a general purpose stash to store cards for these interactions. In doing so I have also created a hand class to allow the 'picking' of cards to place within the stash. Including increments and decrements to increase or decrease the number the player wishes to place at a time.

Added 
- Hand Class (Plus testing)
- Stash Class (Plus testing)
- Inventory Selection Class

Refactored
- Inventory class / Inventory GUI (Combined aspects of both, refactoring the original inventory and making the GUI part only function as the GUI)

## Issue number and link
Reflects the Inventory Card Selection System mentioned in #75

## Screenshots (if appropriate):
image

- Plus and minus symbols representing the selection amount a player wishes to take from a card slot
- The middle box is where the player stashes these cards (Only appears during appropriate actions)
- The check-mark confirms a stash
- The x-mark cancels a stash, resetting it to the inventory

## Types of changes
- [ ] Bug fix (fixes a issue)
- [x] New feature (new implementation of a feature)
- [x] Refactoring (small changes that won't impact very much)
- [x] Possible broken change (fix or feature that could break functionality)

## Checklist:
- [x] Have added comments and documentation
- [x] I have added tests to cover my changes. 
   Or have added an issue that tests need to be added.

### CODE REVIEW

**Comment by CodingAdam** [comment]
Forgot to add tests for Card Selection, will be done soon

**Review by GNAR1ZARD — APPROVED** [review]
The addition of Hand and Stash classes to the card selection feature is a solid enhancement. The refactor of the Inventory and InventoryManager should streamline user interactions. Ensuring these new elements mesh seamlessly with the existing system will be crucial, particularly given the potential for breaking changes. Good work on extending the feature set.

**Review by Nick8120 — APPROVED** [review]
Overall great additions as well as refactors in this PR. The GUI additions look solid.  Removing the monobehavior from the Inventory class should resolve some of the issues with the unit tests for the Inventory Class. Looking into some of the refactors the method name RemoveCardFromGUI could possibly be reworked to better reflect the purpose for the function since it actually removes a card from the stack. I see it is called in the RemoveCardFromStack function but changing the naming conventions is a small improvement that could improve the readability. One other minor thing I noticed is that in RemoveCardFromGUI the method RemoveCardFromStack from the CardStack class is called. This function has the same name as the one that is in the inventory class. A potential name change to the function in the CardStack class to CanRemoveFromStack to align more with the CanAddToStack could again improve readability. Aside from these very minor things you did a great job with such a massive PR. I will be approving this and work on the unit tests for the Inventory Class with these new changes being implemented.

**Comment by Nick8120** [comment]
Nevermind, I see that that the card RemoveCardFromStack was overloaded so ignore the first suggestion.

**Pull request merged**
