### PR TITLE
Added constructor, and basic data gathering for player focused values

### PR DESCRIPTION
**Pull request by CodingAdam**
- Will be referencing things in future, especially from tiles and turnMaster
- Still needs thing like a tile reference system and inventory

### CODE REVIEW

**Comment by CodingAdam** [comment]
Btw, added some comments on the methods in Player class to explain their use and whether they need further additions in future

**Comment by CodingAdam** [comment]
- Also testing methods and testing in general has not been done waiting for pipeline situation to be fixed

**Review by GNAR1ZARD — APPROVED** [review]
The changes made to the Unity script appear to be a refactoring towards a more object-oriented approach, improving data encapsulation and management within the Player class. The introduction of a constructor allows for the initialization of player instances with specific names and colors, which is a good practice in OOP.

**Review by nathalmg — APPROVED** [review]
The changes to the PlayerScript add in a constructor that will allow players to be initialized into the game with name and color values. There are also setters and getters that will be used to interact with other classes to keep track of player turns, tile ownership, and win conditions. This is a good base to continue with our design.

**Pull request merged**
